version: '3'

services:
  api-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - BIND_ADDRESS=0.0.0.0:8080
      - STACKS_NODE_URL=https://stacks-node-api.mainnet.stacks.co
    restart: unless-stopped
